name: bitelens
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.2 # 카메라 사용
  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.6 # 푸드스캐너 AI
  flutter_dotenv: ^5.1.0 # 환경설정
  image_picker: ^1.1.2 # 갤러리
  sqflite: ^2.3.3 # 디바이스 저장
  path: ^1.9.0
  share_plus: ^10.0.0 # 공유
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.0
  image: ^4.1.0

  # Firebase Core
  firebase_core: ^3.10.1

  # Firebase Remote Config
  firebase_remote_config: ^5.5.0

  # Firestore
  cloud_firestore: ^5.6.2

  # Firebase Authentication
  firebase_auth: ^5.4.1
  firebase_auth_web: ^5.13.7
  firebase_analytics: ^11.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

